### ISSUE TITLE
Snapmod - 1.8.3

### ISSUE THREAD

**Issue by jkooper32** [RevealedSoulEven/SnapMod-new#1]
I installed snapmod 1.8.3 that you have posted and also placed the .json file in the directory. So far it seems like the "disable camera" and "enable story list" options are not working.

**Comment by RevealedSoulEven** [comment]
The "disable camera" is working and I've no idea if what does "enable story list" do actually. I just updated it. If it's not working then leave it for now. But you can explain what it does

**Comment by jkooper32** [comment]
Enable story list makes the story tab show stories like it used to be in the old UI. It shows them in a list instead of next to each other in a row.  And it hides the people that you can add as friends also that the story tab started showing.
