### ISSUE TITLE
Snapchat crash

### ISSUE THREAD

**Issue by SodaSiz** [RevealedSoulEven/SnapMod-new#10]
When I launch snapchat with SnapMod enabled, I'm crashing at the startup screen or here:
https://media.discordapp.net/attachments/903002196013101056/1056917308985065512/Screenshot_20221226-135109_Snapchat.png

**Comment by RevealedSoulEven** [comment]
You didn't gave permission 777 to the mappings ( that .json file)

Better go to the mappings and give permission 777
Or put those mappings in /internal storage/Android/xyz.rodit.snapmod/files/
