### ISSUE TITLE
Disable snap splitting not working on 1.8.7

### ISSUE THREAD

**Issue by NMBlanco** [RevealedSoulEven/SnapMod-new#11]
Snaps longer than 10 seconds are split even though the option "disable snap splitting" is enabled.
When I revert back to 1.8.6 it's working again.

**Comment by RevealedSoulEven** [comment]
Is it working for the same version of snapchat but with 1.8.6 snapmod apk? Or you're talking about snapchat 11.92.0.33 ??

**Comment by RevealedSoulEven** [comment]
Still awaiting your response

**Comment by NMBlanco** [comment]
Sorry. Im talking about 12.02.1.33.
Versions before work fine

**Comment by RevealedSoulEven** [comment]
Hmm I see I'll look at it later
