### ISSUE TITLE
No mappings found error

### ISSUE THREAD

**Issue by Aapaar** [RevealedSoulEven/SnapMod-new#12]
Hi! So I've done all the steps, installed lsposed etc. And also installed snapmod 1.8.7. But I'm getting the following error
![Screenshot_20221230_133323_SnapMod](https://user-images.githubusercontent.com/121671155/210070646-3331e587-62ff-404c-9a38-0d96b1678237.jpg)

I know I probably need to install the right mappings. But I wasn't able to find how :(

**Comment by RevealedSoulEven** [comment]
See in the releases page I've provided a .json file. Just put it in Internal Storage/Android/xyz.rodit.snapmod/files/

I've given the step in the readme section
