### ISSUE TITLE
Story section is not working

### ISSUE THREAD

**Issue by Aapaar** [RevealedSoulEven/SnapMod-new#13]
Hi! I successfully installed snapmod.. but when i go to the story page, it stays white? Its not loading. Is this a known bug or am I doing something wrong,

**Comment by RevealedSoulEven** [comment]
![Picsart_23-01-03_00-19-18-142](https://user-images.githubusercontent.com/49313374/210268865-c97cdf66-cbd2-4e63-a617-6d8c594360d4.jpg)
![Picsart_23-01-03_00-20-04-210](https://user-images.githubusercontent.com/49313374/210268874-34427f50-263b-482c-80dd-c190c2108c4e.jpg)

**Comment by Aapaar** [comment]
Thanks, I thought that was supposed to be all unchecked. I've checked the for you box... but now all I see is my friends and subscriptions. The discover below that is still not loading?

**Comment by RevealedSoulEven** [comment]
So you turned it off by clicking "For You"

**Comment by Aapaar** [comment]
Everything was already unchecked.. including the for you box... i now checked the for you box, because you said so. And now all i see is the friends and subscription part.. if i uncheck the for you box, everything goes white again..

**Comment by RevealedSoulEven** [comment]
You'll have to check either of them to make it work, now it's your choice.
I prefer removing the "For You" section, because it's full of crappy videos
that'll waste your productive hours and nothing else
