### ISSUE TITLE
Block ad not working!!

### ISSUE THREAD

**Issue by kalitaka** [RevealedSoulEven/SnapMod-new#14]
I already activated block ads but it's not working I hope u fix it soon, thank u for what u do.
![Screenshot_20230112-020202_Snapchat](https://user-images.githubusercontent.com/113312420/211938138-0334bcad-8ad7-49cb-b3b7-099b070b119f.jpg)

**Comment by RevealedSoulEven** [comment]
No, it doesn't shows for me. Can you please it again

**Comment by kalitaka** [comment]
> No, it doesn't shows for me. Can you please it 

Thank you, it's working now, 
 by the way is there any update soon?
