### ISSUE TITLE
Question regarding project

### ISSUE THREAD

**Issue by vanta240i** [RevealedSoulEven/SnapMod-new#17]
I know this is meant to be a update fork but I was wondering if you could possibly maintain it until the original owner can, or give a tutorial on how to update it ourselves?

**Comment by RevealedSoulEven** [comment]
Me myself learned from exploring rodit's GitHub and reading all documentations of dexsearch. It is enough. Just understand yourself how the project works and that's it.

Also if you're experienced in these stuffs and can find new classes name from the old classes in the mod, you're most welcome to join me and contribute to the mod.

I've very important exams as I'm about to complete my school life next month. So, I'm very busy over there

**Comment by vanta240i** [comment]
As someone currently enrolled in schooling, your situation is completely understandable. I'm good with this stuff so I just wanted to know if you were working on an update already or if I should start making my own update.

**Comment by RevealedSoulEven** [comment]
Easy to start, read the documentation on [XposedLib](https://github.com/rodit/XposedLib)

**Comment by HikaruIchijyo** [comment]
> As someone currently enrolled in schooling, your situation is completely understandable. I'm good with this stuff so I just wanted to know if you were working on an update already or if I should start making my own update.

Have u updated the base?
