### ISSUE TITLE
special characters in username

### ISSUE THREAD

**Issue by JaKrIvMa** [RevealedSoulEven/SnapMod-new#18]
If story/profile name contains any special characters like " / " it wil create a new folder ( or worse, not even save ) so we have to figure out a way to escape all special character in username without screwing things up.

Is this "easy"  to do in some files? haven't done any java / kotlin programming before.

Looking into ways to do it.

**Comment by JaKrIvMa** [comment]
Maybe something like this but better implemented, i am not able to test anything beause i can't set my android studio up right...


[PublicProfileSaving+StoryHelper.zip](https://github.com/RevealedSoulEven/SnapMod-new/files/10611672/PublicProfileSaving%2BStoryHelper.zip)

**Comment by RevealedSoulEven** [comment]
Will fix it later on. But yea here's another new kinda bug🤣
