### ISSUE TITLE
Snapmod settings seems to be missing! 

### ISSUE THREAD

**Issue by Lucky-069** [RevealedSoulEven/SnapMod-new#2]
So I recently came to know about your snapmod continuation and it seems that the most important feature perhaps seems to be missing for me or I can't find it normally, which was available in rodit's version of snapmod! Check the ss below for reference! 
![Screenshot_20220829-182255](https://user-images.githubusercontent.com/78787509/187207924-fed73864-9f9d-47e6-b2dc-1b6051914ae9.png)
So I can't individually pin chats, or set autosave or download option etc.

**Comment by Lucky-069** [comment]
![Screenshot_20220829-182325](https://user-images.githubusercontent.com/78787509/187208496-c6839f5c-8895-4440-a98f-b755a8a94acb.png)

**Comment by Lucky-069** [comment]
So i went through the commits and it seems that the new chat ui option doesn't supports your snapmod settings for some reason, so when I turn off the new chat ui off, it seems to be working! But I would still like to know if it's possible to enable it like the ss above in New chat ui! Because the old chat seems to be too big!

**Comment by Lucky-069** [comment]
![Screenshot_20220829-184717](https://user-images.githubusercontent.com/78787509/187210365-9b547d53-193d-4a1e-b8ff-0b0e08c6ea8f.png)

This is when the new chat ui is turned off in snapmod!

**Comment by Lucky-069** [comment]
It would be actually nice, if you could implement your mod to the new chat ui by default! Because I'm sure a lot of people use the new chat ui!

**Comment by RevealedSoulEven** [comment]
That is the thing I'm trying to do. BTW I that's why modified the snapmod app to make OLD CHAT UI to make those settings work

**Comment by Lucky-069** [comment]
Add it to Readme to turn off the new chat ui, so people don't get confused!

**Comment by RevealedSoulEven** [comment]
Actually by default I set the new chat UI to off in my snapmod apk. So it's not required
