### ISSUE TITLE
Aspect ratio issue

### ISSUE THREAD

**Issue by NMBlanco** [RevealedSoulEven/SnapMod-new#22]
So it seems tnat snapchat made changes to the aspect ratio in the viewfinder. It's messing up all snaps because it doesnt use the full screen anymore.
Do you think you have the ability to add an option that changes it back? In the 12.02 version everything was fine still.

Reference: https://www.reddit.com/r/SnapchatHelp/comments/11num5q/snapchat_issue_how_can_i_change_my_169_aspect/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button
![Screenshot_20230328-212235](https://user-images.githubusercontent.com/12681440/228366146-8e5fae5f-1b2c-4d70-b4e3-fae62159709e.png)

**Comment by RevealedSoulEven** [comment]
Snapchat did it in newer updates and I couldn't figure out if it can be fixed. I'm still using old version of snapchat due to this.

**Comment by NMBlanco** [comment]
> Snapchat did it in newer updates and I couldn't figure out if it can be fixed. I'm still using old version of snapchat due to this.

May I ask on which version you are now?

**Comment by RevealedSoulEven** [comment]
I'm using 11.92.0.33
It's too older but....
For me it's best

**Comment by NMBlanco** [comment]
@RevealedSoulEven yes indeed its the best one but I noticed I'm getting more and more messages from friends that say "not supported, please update to latest snapchat"
:(

**Comment by RevealedSoulEven** [comment]
Yes but those messages are useless too 😂

**Comment by NMBlanco** [comment]
Haha true @RevealedSoulEven 
Would the new snapmod apk be compatible with 11.92 or should I use the old one too?

**Comment by RevealedSoulEven** [comment]
Jse that older one. I'm using 1.8.6
