### ISSUE TITLE
Can't download stories videos

### ISSUE THREAD

**Issue by N013M** [RevealedSoulEven/SnapMod-new#23]
![Screenshot_2023-03-31-00-01-26-142_com android providers downloads ui](https://user-images.githubusercontent.com/104904105/228964317-6e6b63be-53c3-4818-87c8-1391b0a73b30.jpg)
I even tried to turn off "use android download manager"
but didn't work

**Comment by langshaooo** [comment]
I also have the same bug. Only pictures can be saved, not videos. 
Android13, put the mapping file into /storage/emulated/0/Android/data/xyz.rodit.snapmod/files/ or /data/user/0/xyz.rodit.snapmod/files/, open Snapchat and it will crash. It is normal to put it in /storage/emulated/0/Android/data/xyz.rodit.snapmod/files/. So sometimes you have to delete the mapping in /data/, and then restart Snapchat to run normally.

**Comment by Lucky-069** [comment]
Same videos Won't  download. It's hightime rodit just updates the project for good!

**Comment by RevealedSoulEven** [comment]
I'll see it later on. Currently I'm using snapchat 11.92.0.33 due to these

**Comment by RevealedSoulEven** [comment]
https://github.com/rhunk/SnapEnhance
