### ISSUE TITLE
Proper permissions

### ISSUE THREAD

**Issue by ssudac** [RevealedSoulEven/SnapMod-new#26]
Hello, I am wondering the proper permissions for the mapping file. Currently the ones I have set cause Snapchat to crash.

![IMG_20230411_180212.jpg](https://user-images.githubusercontent.com/127074164/231297842-41081455-ec4a-4df6-a5b5-429fdd5017bb.jpg)

**Comment by RevealedSoulEven** [comment]
Give permission 777 or better place the .json to Android data folder in Internal storage. It won't require such permissions
