### ISSUE TITLE
Bro can u give update...

### ISSUE THREAD

**Issue by rahulary** [RevealedSoulEven/SnapMod-new#28]
Nothing is working downloading snap inside the chat and story videos and has many bug in ur latest update so im waiting for new update.....

**Comment by Czernobo** [comment]
You forced me to log in, just so I can reply to your stupid ass. One, don't demand shit from anyone doing something free for you. Two, use the older fucking version. Three, learn how to code if you want shit constantly updated.

**Comment by rahulary** [comment]
> You forced me to log in, just so I can reply to your stupid ass. One, don't demand shit from anyone doing something free for you. Two, use the older fucking version. Three, learn how to code if you want shit constantly updated.

Who the fuck forced here please wear glasses i told im waiting so don't just come here like with hero feel ik how to report things to the maintainer so please mind ur own business...
I asked him before too as he did not reply i mentioned again no one forced anything here.......

**Comment by Czernobo** [comment]
> 

You're special. Don't let anyone else, ever, let you know otherwise.

**Comment by rahulary** [comment]
> > 
> 
> You're special. Don't let anyone else, ever, let you know otherwise.

Read my comment again mind ur own business.....🫠

**Comment by RevealedSoulEven** [comment]
Use https://github.com/rhunk/SnapEnhance
