### ISSUE TITLE
Video sending fails! 

### ISSUE THREAD

**Issue by Lucky-069** [RevealedSoulEven/SnapMod-new#3]
Idk how this happened, but I noticed this. Whenever I try to send a video, the sending fails. I have to disable snapmod from the settings only then I can send videos!

**Comment by RevealedSoulEven** [comment]
Use snapchat 11.92.0.33 with respected snapmod. The newer version of snapchat are buggy and I'm on it to fix it. But still no chance. As I ain't the original developer of the project so it's hard for me to figure out the snapmod workings.

**Comment by Lucky-069** [comment]
I was using 11.92.0.33 only but I experienced the video sending issue
