### ISSUE TITLE
Saving snaps in camera roll failed.

### ISSUE THREAD

**Issue by Xentron9** [RevealedSoulEven/SnapMod-new#4]
There's this issue which doesn't save snaps to camera roll and notifies that it failed.

**Comment by RevealedSoulEven** [comment]
Yes, the error comes in version 11.94 and above. If you use snapchat 11.92 with the previous releases, all features are working well. 
I'm too waiting for the owner to give an update for that which is coming soon. So till then please use Snapchat 11.92.0.33
