### ISSUE TITLE
Video can't be sent in this version too

### ISSUE THREAD

**Issue by amangupta-kf** [RevealedSoulEven/SnapMod-new#5]
Whenever module is enabled, any video snap can't be sent not from snap nor from gallery

**Comment by Radzi11** [comment]
install lower versions.

**Comment by amangupta-kf** [comment]
@Radzi11 Which version are you on I tried the Snpachat 11.94.0.30 Beta with 1.8.4 and 98520.json

**Comment by Radzi11** [comment]
1.8.3 works flawlessly

**Comment by RevealedSoulEven** [comment]
See the New version I just posted. Actually I have less knowledge in Reverse Engineering and I can't clearly figure out the issue. For now I've also fixed some previous bugs and downgraded SnapMod to Snapchat 11.92.0.33 till the original developer fixes everything.
