### ISSUE TITLE
when i wants to download a snap video , Snapchat freeze

### ISSUE THREAD

**Issue by Radzi11** [RevealedSoulEven/SnapMod-new#7]
As in the subject. I don't know why but when I want to download a snap video. Snapchat is stopped. It works randomly, but from what I noticed, it happens when someone sends me a video from iPhone. I am using the last version. Xiaomi mi10 stable miui and A12

**Comment by RevealedSoulEven** [comment]
Please see if you gave storage permission to snapmod. Although it's not required, but sometimes it causes a problem. Also I'm using it on android 13 and it's working fine

**Comment by RevealedSoulEven** [comment]
Even used it on MIUI poco x4 pro
